// Data soal Calistung
const CATEGORIES = [
  {
    id: "warna",
    label: "Tebak Warna",
    icon: "🎨",
    count: 5,
    questions: [
      {
        q: "Warna apa ini? 🔴",
        img: "🔴",
        type: "Tebak Warna",
        options: [
          { label: "Merah", icon: "🔴" },
          { label: "Biru", icon: "🔵" },
          { label: "Hijau", icon: "🟢" },
          { label: "Kuning", icon: "🟡" },
        ],
        correct: 0,
        hint: "Warna apel dan tomat!",
      },
      {
        q: "Warna apa ini? 🟡",
        img: "🟡",
        type: "Tebak Warna",
        options: [
          { label: "Ungu", icon: "🟣" },
          { label: "Kuning", icon: "🟡" },
          { label: "Oranye", icon: "🟠" },
          { label: "Putih", icon: "⚪" },
        ],
        correct: 1,
        hint: "Warna matahari dan pisang!",
      },
      {
        q: "Warna apa ini? 🔵",
        img: "🔵",
        type: "Tebak Warna",
        options: [
          { label: "Merah", icon: "🔴" },
          { label: "Hijau", icon: "🟢" },
          { label: "Biru", icon: "🔵" },
          { label: "Coklat", icon: "🟤" },
        ],
        correct: 2,
        hint: "Warna langit dan laut!",
      },
      {
        q: "Warna apa ini? 🟢",
        img: "🟢",
        type: "Tebak Warna",
        options: [
          { label: "Merah", icon: "🔴" },
          { label: "Hijau", icon: "🟢" },
          { label: "Biru", icon: "🔵" },
          { label: "Kuning", icon: "🟡" },
        ],
        correct: 1,
        hint: "Warna pohon dan rumput!",
      },
      {
        q: "Warna apa ini? 🟠",
        img: "🟠",
        type: "Tebak Warna",
        options: [
          { label: "Oranye", icon: "🟠" },
          { label: "Merah", icon: "🔴" },
          { label: "Hijau", icon: "🟢" },
          { label: "Ungu", icon: "🟣" },
        ],
        correct: 0,
        hint: "Warna jeruk manis!",
      },
    ],
  },
  {
    id: "bentuk",
    label: "Tebak Bentuk",
    icon: "🔷",
    count: 5,
    questions: [
      {
        q: "Bentuk apakah ini?",
        img: "⭕",
        type: "Tebak Bentuk",
        options: [
          { label: "Lingkaran", icon: "⭕" },
          { label: "Kotak", icon: "🟥" },
          { label: "Segitiga", icon: "🔺" },
          { label: "Bintang", icon: "⭐" },
        ],
        correct: 0,
        hint: "Tidak ada sudut, bulat sempurna!",
      },
      {
        q: "Bentuk apakah ini?",
        img: "🟥",
        type: "Tebak Bentuk",
        options: [
          { label: "Lingkaran", icon: "⭕" },
          { label: "Persegi", icon: "🟥" },
          { label: "Segitiga", icon: "🔺" },
          { label: "Berlian", icon: "🔷" },
        ],
        correct: 1,
        hint: "Mempunyai 4 sisi yang sama panjang!",
      },
      {
        q: "Bentuk apakah ini?",
        img: "🔺",
        type: "Tebak Bentuk",
        options: [
          { label: "Oval", icon: "🥚" },
          { label: "Kotak", icon: "🟥" },
          { label: "Segitiga", icon: "🔺" },
          { label: "Persegi Panjang", icon: "▬" },
        ],
        correct: 2,
        hint: "Mempunyai 3 sudut!",
      },
      {
        q: "Bentuk apakah ini?",
        img: "⭐",
        type: "Tebak Bentuk",
        options: [
          { label: "Bunga", icon: "🌸" },
          { label: "Bintang", icon: "⭐" },
          { label: "Matahari", icon: "☀️" },
          { label: "Berlian", icon: "🔷" },
        ],
        correct: 1,
        hint: "Sering kita lihat di langit malam!",
      },
      {
        q: "Bentuk apakah ini?",
        img: "🔷",
        type: "Tebak Bentuk",
        options: [
          { label: "Lingkaran", icon: "⭕" },
          { label: "Segitiga", icon: "🔺" },
          { label: "Berlian", icon: "🔷" },
          { label: "Persegi", icon: "🟥" },
        ],
        correct: 2,
        hint: "Seperti batu permata berharga!",
      },
    ],
  },
  {
    id: "hewan",
    label: "Mengenal Hewan",
    icon: "🐾",
    count: 5,
    questions: [
      {
        q: "Hewan apa ini?",
        img: "🐘",
        type: "Mengenal Hewan",
        options: [
          { label: "Singa", icon: "🦁" },
          { label: "Gajah", icon: "🐘" },
          { label: "Kuda", icon: "🐴" },
          { label: "Sapi", icon: "🐄" },
        ],
        correct: 1,
        hint: "Hewan terbesar di darat, punya belalai panjang!",
      },
      {
        q: "Hewan apa ini?",
        img: "🦁",
        type: "Mengenal Hewan",
        options: [
          { label: "Macan", icon: "🐯" },
          { label: "Kucing", icon: "🐱" },
          { label: "Singa", icon: "🦁" },
          { label: "Serigala", icon: "🐺" },
        ],
        correct: 2,
        hint: "Raja hutan yang gagah!",
      },
      {
        q: "Hewan apa ini?",
        img: "🐧",
        type: "Mengenal Hewan",
        options: [
          { label: "Burung", icon: "🐦" },
          { label: "Bebek", icon: "🦆" },
          { label: "Ayam", icon: "🐔" },
          { label: "Penguin", icon: "🐧" },
        ],
        correct: 3,
        hint: "Hidup di salju dan tidak bisa terbang!",
      },
      {
        q: "Hewan apa ini?",
        img: "🐬",
        type: "Mengenal Hewan",
        options: [
          { label: "Ikan", icon: "🐟" },
          { label: "Hiu", icon: "🦈" },
          { label: "Lumba-lumba", icon: "🐬" },
          { label: "Paus", icon: "🐋" },
        ],
        correct: 2,
        hint: "Hewan laut yang pintar dan suka melompat!",
      },
      {
        q: "Hewan apa ini?",
        img: "🦋",
        type: "Mengenal Hewan",
        options: [
          { label: "Lebah", icon: "🐝" },
          { label: "Lalat", icon: "🪰" },
          { label: "Kupu-kupu", icon: "🦋" },
          { label: "Belalang", icon: "🦗" },
        ],
        correct: 2,
        hint: "Muncul dari kepompong, sayapnya indah!",
      },
    ],
  },
  {
    id: "buah",
    label: "Mengenal Buah",
    icon: "🍎",
    count: 5,
    questions: [
      {
        q: "Buah apa ini?",
        img: "🍎",
        type: "Mengenal Buah",
        options: [
          { label: "Apel", icon: "🍎" },
          { label: "Tomat", icon: "🍅" },
          { label: "Stroberi", icon: "🍓" },
          { label: "Ceri", icon: "🍒" },
        ],
        correct: 0,
        hint: "Buah merah yang renyah!",
      },
      {
        q: "Buah apa ini?",
        img: "🍌",
        type: "Mengenal Buah",
        options: [
          { label: "Mangga", icon: "🥭" },
          { label: "Pisang", icon: "🍌" },
          { label: "Pepaya", icon: "🍈" },
          { label: "Nanas", icon: "🍍" },
        ],
        correct: 1,
        hint: "Monyet suka makan buah ini, berwarna kuning!",
      },
      {
        q: "Buah apa ini?",
        img: "🍇",
        type: "Mengenal Buah",
        options: [
          { label: "Bluberi", icon: "🫐" },
          { label: "Anggur", icon: "🍇" },
          { label: "Plum", icon: "🫒" },
          { label: "Ceri", icon: "🍒" },
        ],
        correct: 1,
        hint: "Buah ungu yang tumbuh berkelompok!",
      },
      {
        q: "Buah apa ini?",
        img: "🍉",
        type: "Mengenal Buah",
        options: [
          { label: "Melon", icon: "🍈" },
          { label: "Semangka", icon: "🍉" },
          { label: "Alpukat", icon: "🥑" },
          { label: "Jeruk", icon: "🍊" },
        ],
        correct: 1,
        hint: "Hijau di luar, merah di dalam, banyak airnya!",
      },
      {
        q: "Buah apa ini?",
        img: "🍍",
        type: "Mengenal Buah",
        options: [
          { label: "Durian", icon: "🌵" },
          { label: "Mangga", icon: "🥭" },
          { label: "Nanas", icon: "🍍" },
          { label: "Kelapa", icon: "🥥" },
        ],
        correct: 2,
        hint: "Buah berduri dengan mahkota daun di atas!",
      },
    ],
  },
  {
    id: "huruf",
    label: "Huruf & Angka",
    icon: "🔤",
    count: 5,
    questions: [
      {
        q: "Huruf apakah ini?",
        img: "🅰️",
        type: "Huruf & Angka",
        options: [
          { label: "A" },
          { label: "B" },
          { label: "C" },
          { label: "D" },
        ],
        correct: 0,
        hint: "Huruf pertama dalam alfabet!",
      },
      {
        q: "Angka berapa ini?",
        img: "5️⃣",
        type: "Huruf & Angka",
        options: [
          { label: "3" },
          { label: "7" },
          { label: "5" },
          { label: "8" },
        ],
        correct: 2,
        hint: "Jari tangan kita ada 5!",
      },
      {
        q: "Huruf apakah ini?",
        img: "🅱️",
        type: "Huruf & Angka",
        options: [
          { label: "P" },
          { label: "B" },
          { label: "D" },
          { label: "R" },
        ],
        correct: 1,
        hint: "Bola namanya diawali huruf ini!",
      },
      {
        q: "Angka berapa ini?",
        img: "🔟",
        type: "Huruf & Angka",
        options: [
          { label: "8" },
          { label: "9" },
          { label: "10" },
          { label: "6" },
        ],
        correct: 2,
        hint: "Jari tangan kiri + kanan = ?",
      },
      {
        q: 'Huruf apa yang bunyi "Ka"?',
        img: "🔤",
        type: "Huruf & Angka",
        options: [
          { label: "G" },
          { label: "K" },
          { label: "C" },
          { label: "Q" },
        ],
        correct: 1,
        hint: "Kucing diawali bunyi ini!",
      },
    ],
  },
  {
    id: "hitung",
    label: "Hitung Benda",
    icon: "🔢",
    count: 5,
    questions: [
      {
        q: "Ada berapa bintang?",
        img: "⭐⭐⭐",
        type: "Hitung Benda",
        options: [
          { label: "2" },
          { label: "3" },
          { label: "4" },
          { label: "5" },
        ],
        correct: 1,
        hint: "Hitunglah satu per satu!",
      },
      {
        q: "Ada berapa apel?",
        img: "🍎🍎🍎🍎🍎",
        type: "Hitung Benda",
        options: [
          { label: "3" },
          { label: "4" },
          { label: "5" },
          { label: "6" },
        ],
        correct: 2,
        hint: "Jari tanganmu satu tangan!",
      },
      {
        q: "Ada berapa balon?",
        img: "🎈🎈",
        type: "Hitung Benda",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "4" },
        ],
        correct: 1,
        hint: "Hitunglah dengan pelan!",
      },
      {
        q: "Ada berapa kupu-kupu?",
        img: "🦋🦋🦋🦋",
        type: "Hitung Benda",
        options: [
          { label: "2" },
          { label: "3" },
          { label: "4" },
          { label: "5" },
        ],
        correct: 2,
        hint: "Hitunglah gambarnya!",
      },
      {
        q: "Ada berapa ikan?",
        img: "🐟🐟🐟🐟🐟🐟",
        type: "Hitung Benda",
        options: [
          { label: "4" },
          { label: "5" },
          { label: "6" },
          { label: "7" },
        ],
        correct: 2,
        hint: "Enam = setengah dari dua belas!",
      },
    ],
  },
  {
    id: "matematika",
    label: "Penjumlahan",
    icon: "➕",
    count: 5,
    questions: [
      {
        q: "1 + 1 = ?",
        img: "🍎 + 🍎",
        type: "Matematika",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "4" },
        ],
        correct: 1,
        hint: "Satu apel ditambah satu apel!",
      },
      {
        q: "2 + 2 = ?",
        img: "🐣🐣 + 🐣🐣",
        type: "Matematika",
        options: [
          { label: "3" },
          { label: "4" },
          { label: "5" },
          { label: "6" },
        ],
        correct: 1,
        hint: "Gunakan jari tanganmu untuk menghitung!",
      },
      {
        q: "3 + 1 = ?",
        img: "⭐⭐⭐ + ⭐",
        type: "Matematika",
        options: [
          { label: "3" },
          { label: "5" },
          { label: "4" },
          { label: "6" },
        ],
        correct: 2,
        hint: "Tiga bintang ditambah satu bintang!",
      },
      {
        q: "2 + 3 = ?",
        img: "🐟🐟 + 🐟🐟🐟",
        type: "Matematika",
        options: [
          { label: "4" },
          { label: "6" },
          { label: "5" },
          { label: "7" },
        ],
        correct: 2,
        hint: "Dua ikan ditambah tiga ikan!",
      },
      {
        q: "4 + 1 = ?",
        img: "🌸🌸🌸🌸 + 🌸",
        type: "Matematika",
        options: [
          { label: "4" },
          { label: "5" },
          { label: "6" },
          { label: "3" },
        ],
        correct: 1,
        hint: "Empat bunga ditambah satu bunga!",
      },
    ],
  },
  {
    id: "pengurangan",
    label: "Pengurangan",
    icon: "➖",
    count: 5,
    questions: [
      {
        q: "3 - 1 = ?",
        img: "🍎🍎🍎 - 🍎",
        type: "Matematika",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "4" },
        ],
        correct: 1,
        hint: "Tiga dikurangi satu!",
      },
      {
        q: "4 - 2 = ?",
        img: "🌟🌟🌟🌟 - 🌟🌟",
        type: "Matematika",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "4" },
        ],
        correct: 1,
        hint: "Empat bintang dikurangi dua bintang!",
      },
      {
        q: "5 - 3 = ?",
        img: "🐥🐥🐥🐥🐥 - 🐥🐥🐥",
        type: "Matematika",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "4" },
        ],
        correct: 1,
        hint: "Lima dikurangi tiga!",
      },
      {
        q: "3 - 2 = ?",
        img: "🍓🍓🍓 - 🍓🍓",
        type: "Matematika",
        options: [
          { label: "1" },
          { label: "2" },
          { label: "3" },
          { label: "0" },
        ],
        correct: 0,
        hint: "Tiga dikurangi dua tersisa?",
      },
      {
        q: "5 - 1 = ?",
        img: "🐠🐠🐠🐠🐠 - 🐠",
        type: "Matematika",
        options: [
          { label: "3" },
          { label: "4" },
          { label: "5" },
          { label: "6" },
        ],
        correct: 1,
        hint: "Lima ikan dikurangi satu ikan!",
      },
    ],
  },
];
